/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import cifrados.CifrarContrasena;
import com.mysql.cj.protocol.a.LocalDateTimeValueEncoder;
import dominio.Cliente;
import dominio.Cuenta;
import excepciones.PersistenciaException;
import implementaciones.CuentasDAO;
import interfaces.IClientesDAO;
import interfaces.ICuentasDAO;
import java.sql.Date;
import java.time.LocalDateTime;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import presentacion.TransferenciaForm;


/**
 *
 * @author Cristian
 */
public class Sesión extends javax.swing.JFrame {

    private final IClientesDAO clientesDAO;
    private final ICuentasDAO cuentasDAO;
    private Cliente cliente;
    /**
     * Creates new form Cuenta
     */
    public Sesión(IClientesDAO clientesDAO, ICuentasDAO cuentasDAO, Cliente cliente) {
        this.setTitle("Cuenta");
        this.cliente = cliente;
        this.clientesDAO = clientesDAO;
        this.cuentasDAO = cuentasDAO;
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        txtCliente.setEditable(false);
 
        
    }
    public final int idDelCliente(){
        int id = Integer.parseInt(IniciarSesion.txtId.getText());
        txtCliente.setText(IniciarSesion.txtId.getText());
        return id;
    }
    
    public Cuenta extraerDatosCuenta() {
         Random random = new Random();
        // Generar un número aleatorio de 16 dígitos en el rango de [10^15, 10^16)
        long numero = (long) (random.nextDouble() * 9e15 + 1e15);
        String numeroString = Long.toString(numero);
        String fechaActual = LocalDateTime.now().toString();
        int id = Integer.parseInt(txtCliente.getText());
        JOptionPane.showMessageDialog(null, "Tu nº Cuenta es: " + numeroString);
        Cuenta cuenta = new Cuenta(fechaActual, "activa", 2000, numeroString, id);
        return cuenta;

    }

    public void abrirCuenta() {
         
            Cuenta cuenta = this.extraerDatosCuenta();
            Cuenta cuentaGuardada = this.cuentasDAO.registrar(cuenta);
            JOptionPane.showMessageDialog(null, "Cuenta creada");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransferir = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnTransacciones = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        menuConfigurar = new javax.swing.JMenu();
        menuItemActualizar = new javax.swing.JMenuItem();
        menuItemAbrirCuenta = new javax.swing.JMenuItem();
        menuItemCancelarCuenta = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnTransacciones.setText("Transacciones");
        btnTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionesActionPerformed(evt);
            }
        });

        lblNombre.setText("Cliente");

        menuConfigurar.setText("Cuenta");

        menuItemActualizar.setText("Datos Personales");
        menuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarActionPerformed(evt);
            }
        });
        menuConfigurar.add(menuItemActualizar);

        menuItemAbrirCuenta.setText("Abrir Cuenta");
        menuItemAbrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirCuentaActionPerformed(evt);
            }
        });
        menuConfigurar.add(menuItemAbrirCuenta);

        menuItemCancelarCuenta.setText("Cancelar Cuenta");
        menuItemCancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCancelarCuentaActionPerformed(evt);
            }
        });
        menuConfigurar.add(menuItemCancelarCuenta);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuConfigurar.add(menuItemSalir);

        menu.add(menuConfigurar);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransferir)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTransacciones))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnTransferir)
                .addGap(18, 18, 18)
                .addComponent(btnRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnTransacciones)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarActionPerformed
        // TODO add your handling code here:
        ActualizarDatos ad = new ActualizarDatos(clientesDAO, cuentasDAO, cliente);
        dispose();
        ad.setVisible(true);

    }//GEN-LAST:event_menuItemActualizarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        TransferenciaForm tf = new TransferenciaForm(clientesDAO, cuentasDAO, cliente);
        dispose();
       tf.setVisible(true);
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
        dispose();
        new RetiroCliente(clientesDAO, cuentasDAO, cliente).setVisible(true);
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        new Inicio(clientesDAO,cuentasDAO,cliente).setVisible(true);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemCancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCancelarCuentaActionPerformed
        // TODO add your handling code here:
//        Cuenta cuenta = new Cuenta();
//        cuenta.setEstado("desactivada");
    }//GEN-LAST:event_menuItemCancelarCuentaActionPerformed

    private void btnTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionesActionPerformed
        // TODO add your handling code here:
        dispose();
        new Historial(clientesDAO,cuentasDAO,cliente).setVisible(true);
        
    }//GEN-LAST:event_btnTransaccionesActionPerformed

    private void menuItemAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirCuentaActionPerformed

            // TODO add your handling code here:
            abrirCuenta();
  
    }//GEN-LAST:event_menuItemAbrirCuentaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuConfigurar;
    private javax.swing.JMenuItem menuItemAbrirCuenta;
    private javax.swing.JMenuItem menuItemActualizar;
    private javax.swing.JMenuItem menuItemCancelarCuenta;
    private javax.swing.JMenuItem menuItemSalir;
    public static javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
